<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MediatR" Version="12.4.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.11">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.4.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\KovserHediyyeler.Persistence\KovserHediyyeler.Persistence.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="wwwroot\Assets\Files\InvoiceFiles\" />
    <Folder Include="wwwroot\Assets\Images\Brands\" />
    <Folder Include="wwwroot\Assets\Images\Departments\" />
    <Folder Include="wwwroot\Assets\Images\Promotions\" />
    <Folder Include="wwwroot\Assets\Images\SocialMedias\" />
  </ItemGroup>

  <ItemGroup>
    <None Include="wwwroot\Assets\Images\Products\e5d53172-04a5-4bac-9224-abe22d4734b9png-transparent-paper-stationery-office-supplies-school-supplies-retail-school-pencil-retail-school-supplies-t.png" />
    <None Include="wwwroot\Assets\Images\Products\f0e1bc4c-4265-4674-a8c9-8c5da8afb35cpng-transparent-paper-stationery-office-supplies-school-supplies-retail-school-pencil-retail-school-supplies-t.png" />
  </ItemGroup>

</Project>
